### List all countdowns
GET http://localhost/bb-melhor-envio/wp-json/clockdown/v1/countdowns

### Create a countdown
POST http://localhost/bb-melhor-envio/wp-json/clockdown/v1/countdowns
content-type: application/json

{
    "name": "countdown 3",
    "description": "Countdown description"
}

### Get the countdown with id 1
GET http://localhost/bb-melhor-envio/wp-json/clockdown/v1/countdowns/16


### Update the countdown with id 1
PUT http://localhost/bb-melhor-envio/wp-json/clockdown/v1/countdowns/16
content-type: application/json

{
    "name": "countdown number 2",
    "description": "Qui dolor duis amet excepteur. Magna cupidatat cupidatat adipisicing laboris irure irure. Excepteur deserunt ad incididunt occaecat ad labore. "
}

### Delete the countdown with id 1
DELETE http://localhost/bb-melhor-envio/wp-json/clockdown/v1/countdowns/1


### Get the countdown settings with id 2
GET http://localhost/bb-melhor-envio/wp-json/clockdown/v1/countdowns/19/settings

### Create a countdown settings for the countdown with id 2
POST http://localhost/bb-melhor-envio/wp-json/clockdown/v1/countdowns/43/settings
content-type: application/json

{"countdown_id":46,"settings":{"targetDate":"2022-12-31T23:00","targetTimezone":"Europe/Berlin","unitLabelLanguage":"en-US","global":{"containerSize":{"width":341,"height":67}},"timer":{"unitsShown":["dd","hh","mm","ss"],"showSeparator":true,"separatorChar":":","digitFontFamily":"Inter","digitFontWeight":"400","digitFontSize":{"sm":14,"md":16,"lg":18},"digitFontColor":"#000000","lastUnitColor":"#e10b0b","labelFontFamily":"Inter","labelFontWeight":"400","labelFontSize":{"sm":14,"md":16,"lg":18},"labelFontColor":"#000000"},"title":{"text":"Countdown to New Year","fontFamily":"Inter","fontWeight":"400","fontSize":{"sm":14,"md":16,"lg":18},"fontColor":"#000000"}}}

### Update a countdown settings for the countdown with id 2
PUT http://localhost/bb-melhor-envio/wp-json/clockdown/v1/countdowns/49/settings
content-type: application/json

{"countdown_id":49,"settings":{"targetDate":"2022-12-31T23:00","targetTimezone":"Europe/Berlin","unitLabelLanguage":"en-US","global":{"containerSize":{"width":341,"height":67}},"timer":{"unitsShown":["dd","hh","mm","ss"],"showSeparator":true,"separatorChar":":","digitFontFamily":"Inter","digitFontWeight":"400","digitFontSize":{"sm":14,"md":16,"lg":18},"digitFontColor":"#000000","lastUnitColor":"#e10b0b","labelFontFamily":"Inter","labelFontWeight":"400","labelFontSize":{"sm":14,"md":16,"lg":18},"labelFontColor":"#000000"},"title":{"text":"Countdown to New Year","fontFamily":"Inter","fontWeight":"400","fontSize":{"sm":14,"md":16,"lg":18},"fontColor":"#000000"}}}

### Delete the countdown settings with id 19
DELETE http://localhost/bb-melhor-envio/wp-json/clockdown/v1/countdowns/17/settings

### Get the last countdown mutated
GET http://localhost/bb-melhor-envio/wp-json/clockdown/v1/countdowns/last/settings