### List all onboarding
GET http://localhost/bb-melhor-envio/wp-json/commerce/v1/onboarding

### Get the installation by id
GET http://localhost/bb-melhor-envio/wp-json/commerce/v1/analytics/installations/7cg9997b-0f40-11ed-9cce-040e3caabadb

### Track new installation
POST http://localhost/bb-melhor-envio/wp-json/commerce/v1/analytics/installations
content-type: application/json

{
    "product_id": 1,
    "installation_id": "7cg9997b-0f40-11ed-9cce-040e3caabadb",
    "site_url": "http://localhost",
    "site_language": "Portoguese",
    "site_timezone": "America/Sao_Paulo"
}

### "installation_id": "3be6607b-0f40-11ed-9cce-040e3caabadb",


### Create an onboarding
POST http://localhost/bb-melhor-envio/wp-json/commerce/v1/onboarding
content-type: application/json

{
    "fullname": "Johnny Doenza",
    "email": "johnny@gmail.com!",
    "consent_newsletter": true,
    "consent_terms": true,
    "consent_privacy": true,
    "product_id": 1,
    "installation_id": "7cg9997b-0f40-11ed-9cce-040e3caabadb"
}

### "installation_id": "3be6607b-0f40-11ed-9cce-040e3caabadb"

###
POST http://localhost/bb-melhor-envio/wp-json/commerce/v1/onboarding/2
content-type: application/json

{
    "fullname": "Pippolo"
}