import { Templates } from "../types";

export const TEMPLATES_BASE_ASSET_PATH =
  "/src/editor/editor-properties/properties/templates-properties-group/assets/";

export const TEMPLATES: Templates = {
  default: {
    id: "default",
    name: "Default",
    style: `div[data-element=countdown-units],div[data-element=countdown-widget],div[data-element=countdown-wrapper]{display:-webkit-box;display:-webkit-flex;display:-ms-flexbox}h2[data-element=countdown-title],span[data-element=countdown-unit-label],span[data-element=countdown-unit-number]{font-size:16px;font-weight:400;font-family:Inter}a[data-element=countdown-link-wrapper]{color:inherit;-webkit-text-decoration:none;text-decoration:none}div[data-element=countdown-widget]{display:flex;-ms-flex-wrap:wrap;flex-wrap:wrap;-webkit-justify-content:center;justify-content:center;width:100%}div[data-element=countdown-container]{width:100%}div[data-element=countdown-wrapper]{display:flex;-ms-flex-wrap:wrap;flex-wrap:wrap;-webkit-align-items:center;-webkit-box-align:center;-ms-flex-align:center;align-items:center;-webkit-flex-direction:column;-ms-flex-direction:column;flex-direction:column;-webkit-justify-content:space-evenly;justify-content:space-evenly;gap:1.5rem;padding:1rem .5rem;width:max-content;background:#fff}h2[data-element=countdown-title]{margin:0;line-height:1.3;text-align:center}div[data-element=countdown-units]{display:flex;-ms-flex-wrap:wrap;flex-wrap:wrap;-webkit-align-items:center;-webkit-box-align:center;-ms-flex-align:center;align-items:center;-webkit-flex-direction:row;-ms-flex-direction:row;flex-direction:row}div[data-element=countdown-unit]{display:grid;grid-template-areas:"number separator" "label empty";-webkit-align-items:center;-webkit-box-align:center;-ms-flex-align:center;align-items:center;justify-items:center}span[data-element=countdown-unit-number]{text-rendering:optimizeSpeed;grid-area:number}span[data-element=countdown-unit-label]{line-height:1.1;text-rendering:optimizeSpeed;grid-area:label}div[data-element=countdown-unit][data-unit-type=separator]{text-rendering:optimizeSpeed}div[data-element=countdown-unit]:last-child{color:#e10b0b}`,
    image: "default",
    fontFamily: "Inter",
    orientation: "vertical",
  },
  defaultHorizontal: {
    id: "defaultHorizontal",
    name: "Default Horizontal",
    style: `div[data-element=countdown-units],div[data-element=countdown-widget],div[data-element=countdown-wrapper]{display:-webkit-box;display:-webkit-flex;display:-ms-flexbox}h2[data-element=countdown-title],span[data-element=countdown-unit-label],span[data-element=countdown-unit-number]{font-size:16px;font-weight:400;font-family:Inter}a[data-element=countdown-link-wrapper]{color:inherit;-webkit-text-decoration:none;text-decoration:none}div[data-element=countdown-widget]{display:flex;-ms-flex-wrap:wrap;flex-wrap:wrap;-webkit-justify-content:center;justify-content:center;width:100%}div[data-element=countdown-container]{width:100%}div[data-element=countdown-wrapper]{display:flex;-ms-flex-wrap:wrap;flex-wrap:wrap;-webkit-align-items:center;-webkit-box-align:center;-ms-flex-align:center;align-items:center;-webkit-flex-direction:column;-ms-flex-direction:column;flex-direction:column;-webkit-justify-content:space-evenly;justify-content:space-evenly;gap:1.5rem;padding:1rem .5rem;width:max-content;background:#fff}h2[data-element=countdown-title]{margin:0;line-height:1.3;text-align:center}div[data-element=countdown-units]{display:flex;-ms-flex-wrap:wrap;flex-wrap:wrap;-webkit-align-items:center;-webkit-box-align:center;-ms-flex-align:center;align-items:center;-webkit-flex-direction:row;-ms-flex-direction:row;flex-direction:row}div[data-element=countdown-unit]{display:grid;grid-template-areas:"number separator" "label empty";-webkit-align-items:center;-webkit-box-align:center;-ms-flex-align:center;align-items:center;justify-items:center}span[data-element=countdown-unit-number]{text-rendering:optimizeSpeed;grid-area:number}span[data-element=countdown-unit-label]{line-height:1.1;text-rendering:optimizeSpeed;grid-area:label}div[data-element=countdown-unit][data-unit-type=separator]{text-rendering:optimizeSpeed}div[data-element=countdown-unit]:last-child{color:#e10b0b}`,
    image: "default-horizontal",
    fontFamily: "Inter",
    orientation: "horizontal",
  },
  monospace: {
    id: "monospace",
    name: "Monospace",
    style: `a[data-element=countdown-link-wrapper]{color:inherit;-webkit-text-decoration:none;text-decoration:none}div[data-element=countdown-wrapper]{display:-webkit-flex;display:-ms-flexbox;display:flex;-webkit-flex-direction:column;-ms-flex-direction:column;flex-direction:column;background-color:#8a2be2;max-width:375px;gap:.75rem;font-family:monospace;padding:1rem;border-radius:5px}h2[data-element=countdown-title]{text-align:center;color:#fff;font-weight:700;font-size:2rem}div[data-element=countdown-units]{display:-ms-grid;display:grid;grid-template-columns:repeat(4,1fr);gap:.5rem}div[data-element=countdown-unit]{display:-webkit-flex;display:-ms-flexbox;display:flex;-webkit-flex-direction:column;-ms-flex-direction:column;gap:.25rem;flex-direction:column}span[data-element=countdown-unit-number]{background-color:#fff;padding:1rem;border-radius:10px;text-align:center;font-size:1.5rem}span[data-element=countdown-unit-label]{text-align:center;color:#fff;font-size:1.15rem}div[data-unit-type=separator],span[data-element=countdown-unit-separator]{display:none}`,
    image: "monospace",
    orientation: "vertical",
  },
  monospaceHorizontal: {
    id: "monospaceHorizontal",
    name: "Monospace Horizontal",
    style: `div[data-element=countdown-units],div[data-element=countdown-widget],div[data-element=countdown-wrapper]{display:-webkit-box;display:-webkit-flex;display:-ms-flexbox}h2[data-element=countdown-title],span[data-element=countdown-unit-label],span[data-element=countdown-unit-number]{font-size:16px;font-weight:400;font-family:monospace}a[data-element=countdown-link-wrapper]{color:inherit;-webkit-text-decoration:none;text-decoration:none}div[data-element=countdown-widget]{display:flex;-ms-flex-wrap:wrap;flex-wrap:wrap;-webkit-justify-content:center;justify-content:center;width:100%}div[data-element=countdown-container]{width:100%;display:flex;justify-content:center;background-color:#8a2be2}div[data-element=countdown-wrapper]{display:flex;-ms-flex-wrap:wrap;flex-wrap:wrap;-webkit-align-items:center;-webkit-box-align:center;-ms-flex-align:center;align-items:center;-webkit-flex-direction:column;-ms-flex-direction:column;flex-direction:column;-webkit-justify-content:space-evenly;justify-content:space-evenly;gap:1.5rem;padding:1rem .5rem;width:375px;gap:.5rem}h2[data-element=countdown-title]{margin:0;line-height:1.3;text-align:center;font-weight:700;text-transform:uppercase;color:#fff;font-size:1.15rem}div[data-element=countdown-units]{-ms-layout-grid:grid;display:grid;-ms-grid-template-column:repeat(4,1fr);grid-template-columns:repeat(4,1fr);gap:1rem}div[data-element=countdown-unit]{display:grid;grid-template-areas:"number" "label";-webkit-align-items:center;-webkit-box-align:center;-ms-flex-align:center;align-items:center;justify-items:center;gap:.25rem}span[data-element=countdown-unit-number]{text-rendering:optimizeSpeed;grid-area:number;font-size:1.5rem;font-weight:700;letter-spacing:-.5px;color:#000;background-color:#fff;display:flex;justify-content:center;align-items:center;border-radius:.25rem;width:100%;min-height:2rem}span[data-element=countdown-unit-label]{line-height:1.1;text-rendering:optimizeSpeed;grid-area:label;font-size:.95rem;text-transform:lowercase;letter-spacing:-.25px;color:#fff;text-align:center}div[data-element=countdown-unit][data-unit-type=separator]{display:none}div[data-element=countdown-unit]:last-child{color:#e10b0b}@media (min-width:768px){div[data-element=countdown-container]{display:flex;justify-content:center}div[data-element=countdown-wrapper]{-webkit-flex-direction:row;-ms-flex-direction:row;flex-direction:row;padding:.5rem 0;width:100%;max-width:978px}h2[data-element=countdown-title]{max-width:60%;text-align:left}span[data-element=countdown-unit-number]{font-size:1.25rem}}`,
    image: "monospace-horizontal",
    orientation: "horizontal",
  },
  greeny: {
    id: "greeny",
    name: "Greeny",
    style: `div[data-element=countdown-units],div[data-element=countdown-widget],div[data-element=countdown-wrapper]{display:-webkit-box;display:-webkit-flex;display:-ms-flexbox}h2[data-element=countdown-title],span[data-element=countdown-unit-label],span[data-element=countdown-unit-number]{font-size:16px;font-weight:400;font-family:Oswald,Arial,sans-serif}a[data-element=countdown-link-wrapper]{color:inherit;-webkit-text-decoration:none;text-decoration:none}div[data-element=countdown-widget]{display:flex;-ms-flex-wrap:wrap;flex-wrap:wrap;-webkit-justify-content:center;justify-content:center;width:100%}div[data-element=countdown-container]{width:100%}div[data-element=countdown-wrapper]{display:flex;-ms-flex-wrap:wrap;flex-wrap:wrap;-webkit-align-items:center;-webkit-box-align:center;-ms-flex-align:center;align-items:center;-webkit-flex-direction:column;-ms-flex-direction:column;flex-direction:column;-webkit-justify-content:space-evenly;justify-content:space-evenly;gap:1.5rem;padding:1rem .5rem;background:#73f8ba;width:375px;gap:.5rem}h2[data-element=countdown-title]{margin:0;line-height:1.3;text-align:center;font-weight:700;text-transform:uppercase}div[data-element=countdown-units]{display:flex;-ms-flex-wrap:wrap;flex-wrap:wrap;-webkit-align-items:center;-webkit-box-align:center;-ms-flex-align:center;align-items:center;-webkit-flex-direction:row;-ms-flex-direction:row;flex-direction:row;gap:1rem}div[data-element=countdown-unit]{display:grid;grid-template-areas:"number separator" "label empty";-webkit-align-items:center;-webkit-box-align:center;-ms-flex-align:center;align-items:center;justify-items:center;gap:.25rem}span[data-element=countdown-unit-number]{text-rendering:optimizeSpeed;grid-area:number;font-size:1.5rem;font-weight:700;letter-spacing:-.5px;color:#000}span[data-element=countdown-unit-label]{line-height:1.1;text-rendering:optimizeSpeed;grid-area:label;font-size:.75rem;text-transform:lowercase;letter-spacing:-.25px;color:#000}div[data-element=countdown-unit][data-unit-type=separator]{text-rendering:optimizeSpeed}div[data-element=countdown-unit]:last-child{color:#e10b0b}`,
    image: "greeny",
    fontFamily: "Oswald",
    orientation: "vertical",
  },
  greenyHorizontal: {
    id: "greenyHorizontal",
    name: "Greeny Horizontal",
    style: `div[data-element=countdown-units],div[data-element=countdown-widget],div[data-element=countdown-wrapper]{display:-webkit-box;display:-webkit-flex;display:-ms-flexbox}h2[data-element=countdown-title],span[data-element=countdown-unit-label],span[data-element=countdown-unit-number]{font-size:16px;font-weight:400;font-family:Oswald,Arial,sans-serif}a[data-element=countdown-link-wrapper]{color:inherit;-webkit-text-decoration:none;text-decoration:none}div[data-element=countdown-widget]{display:flex;-ms-flex-wrap:wrap;flex-wrap:wrap;-webkit-justify-content:center;justify-content:center;width:100%}div[data-element=countdown-container]{background:#73f8ba;width:100%}div[data-element=countdown-wrapper]{display:flex;-ms-flex-wrap:wrap;flex-wrap:wrap;-webkit-align-items:center;-webkit-box-align:center;-ms-flex-align:center;align-items:center;-webkit-flex-direction:column;-ms-flex-direction:column;flex-direction:column;-webkit-justify-content:space-evenly;justify-content:space-evenly;gap:1.5rem;padding:1rem .5rem;width:375px;gap:.5rem}h2[data-element=countdown-title]{margin:0;line-height:1.3;text-align:center;font-weight:700;text-transform:uppercase}div[data-element=countdown-units]{display:flex;-ms-flex-wrap:wrap;flex-wrap:wrap;-webkit-align-items:center;-webkit-box-align:center;-ms-flex-align:center;align-items:center;-webkit-flex-direction:row;-ms-flex-direction:row;flex-direction:row;gap:1rem}div[data-element=countdown-unit]{display:grid;grid-template-areas:"number separator" "label empty";-webkit-align-items:center;-webkit-box-align:center;-ms-flex-align:center;align-items:center;justify-items:center;gap:.25rem}span[data-element=countdown-unit-number]{text-rendering:optimizeSpeed;grid-area:number;font-size:1.5rem;font-weight:700;letter-spacing:-.5px;color:#000}span[data-element=countdown-unit-label]{line-height:1.1;text-rendering:optimizeSpeed;grid-area:label;font-size:.75rem;text-transform:lowercase;letter-spacing:-.25px;color:#000}div[data-element=countdown-unit][data-unit-type=separator]{text-rendering:optimizeSpeed}div[data-element=countdown-unit]:last-child{color:#e10b0b}@media (min-width:768px){div[data-element=countdown-container]{display:flex;justify-content:center}div[data-element=countdown-wrapper]{-webkit-flex-direction:row;-ms-flex-direction:row;flex-direction:row;padding:.5rem 0;width:100%;max-width:978px}h2[data-element=countdown-title]{max-width:60%;text-align:left}span[data-element=countdown-unit-number]{font-size:1.25rem}}`,
    image: "greeny-horizontal",
    fontFamily: "Oswald",
    orientation: "horizontal",
  },
  spicy: {
    id: "spicy",
    name: "Spicy",
    style: `div[data-element=countdown-units],div[data-element=countdown-widget],div[data-element=countdown-wrapper]{display:-webkit-box;display:-webkit-flex;display:-ms-flexbox}h2[data-element=countdown-title],span[data-element=countdown-unit-label],span[data-element=countdown-unit-number]{font-size:16px;font-weight:400;font-family:"Bungee Spice",cursive}a[data-element=countdown-link-wrapper]{color:inherit;-webkit-text-decoration:none;text-decoration:none}div[data-element=countdown-widget]{display:flex;-ms-flex-wrap:wrap;flex-wrap:wrap;-webkit-justify-content:center;justify-content:center;width:100%}div[data-element=countdown-container]{width:100%}div[data-element=countdown-wrapper]{display:flex;-ms-flex-wrap:wrap;flex-wrap:wrap;-webkit-align-items:center;-webkit-box-align:center;-ms-flex-align:center;align-items:center;-webkit-flex-direction:column;-ms-flex-direction:column;flex-direction:column;-webkit-justify-content:space-evenly;justify-content:space-evenly;gap:1.5rem;padding:1rem .5rem;background:#f7ebe8;width:375px;gap:.5rem}h2[data-element=countdown-title]{margin:0;line-height:1.3;text-align:center;font-weight:700;text-transform:uppercase}div[data-element=countdown-units]{display:flex;-ms-flex-wrap:wrap;flex-wrap:wrap;-webkit-align-items:center;-webkit-box-align:center;-ms-flex-align:center;align-items:center;-webkit-flex-direction:row;-ms-flex-direction:row;flex-direction:row;gap:1rem}div[data-element=countdown-unit]{display:grid;grid-template-areas:"number separator" "label empty";-webkit-align-items:center;-webkit-box-align:center;-ms-flex-align:center;align-items:center;justify-items:center;gap:.25rem}span[data-element=countdown-unit-number]{text-rendering:optimizeSpeed;grid-area:number;font-size:1.5rem;font-weight:700;letter-spacing:-.5px;color:#000}span[data-element=countdown-unit-label]{line-height:1.1;text-rendering:optimizeSpeed;grid-area:label;font-size:.75rem;text-transform:lowercase;letter-spacing:-.25px;color:#000}div[data-element=countdown-unit][data-unit-type=separator]{text-rendering:optimizeSpeed}div[data-element=countdown-unit]:last-child{color:#e10b0b}`,
    image: "spicy",
    fontFamily: "Bungee Spice",
    orientation: "vertical",
  },
  spicyHorizontal: {
    id: "spicyHorizontal",
    name: "Spicy Horizontal",
    style: `div[data-element=countdown-units],div[data-element=countdown-widget],div[data-element=countdown-wrapper]{display:-webkit-box;display:-webkit-flex;display:-ms-flexbox}h2[data-element=countdown-title],span[data-element=countdown-unit-label],span[data-element=countdown-unit-number]{font-size:16px;font-weight:400;font-family:"Bungee Spice",cursive}a[data-element=countdown-link-wrapper]{color:inherit;-webkit-text-decoration:none;text-decoration:none}div[data-element=countdown-widget]{display:flex;-ms-flex-wrap:wrap;flex-wrap:wrap;-webkit-justify-content:center;justify-content:center;width:100%}div[data-element=countdown-container]{width:100%;display:flex;justify-content:center;background-color:#f7ebe8}div[data-element=countdown-wrapper]{display:flex;-ms-flex-wrap:wrap;flex-wrap:wrap;-webkit-align-items:center;-webkit-box-align:center;-ms-flex-align:center;align-items:center;-webkit-flex-direction:column;-ms-flex-direction:column;flex-direction:column;-webkit-justify-content:space-evenly;justify-content:space-evenly;gap:1.5rem;padding:1rem .5rem;background:#f7ebe8;width:375px;gap:.5rem}h2[data-element=countdown-title]{margin:0;line-height:1.3;text-align:center;font-weight:700;text-transform:uppercase}div[data-element=countdown-units]{display:flex;-ms-flex-wrap:wrap;flex-wrap:wrap;-webkit-align-items:center;-webkit-box-align:center;-ms-flex-align:center;align-items:center;-webkit-flex-direction:row;-ms-flex-direction:row;flex-direction:row;gap:1rem}div[data-element=countdown-unit]{display:grid;grid-template-areas:"number separator" "label empty";-webkit-align-items:center;-webkit-box-align:center;-ms-flex-align:center;align-items:center;justify-items:center;gap:.25rem}span[data-element=countdown-unit-number]{text-rendering:optimizeSpeed;grid-area:number;font-size:1.5rem;font-weight:700;letter-spacing:-.5px;color:#000}span[data-element=countdown-unit-label]{line-height:1.1;text-rendering:optimizeSpeed;grid-area:label;font-size:.75rem;text-transform:lowercase;letter-spacing:-.25px;color:#000}div[data-element=countdown-unit][data-unit-type=separator]{text-rendering:optimizeSpeed}div[data-element=countdown-unit]:last-child{color:#e10b0b}@media (min-width:768px){div[data-element=countdown-container]{display:flex;justify-content:center}div[data-element=countdown-wrapper]{-webkit-flex-direction:row;-ms-flex-direction:row;flex-direction:row;padding:.5rem 0;width:100%;max-width:978px}h2[data-element=countdown-title]{max-width:60%;text-align:left}span[data-element=countdown-unit-number]{font-size:1.25rem}}`,
    image: "spicy-horizontal",
    fontFamily: "Bungee Spice",
    orientation: "horizontal",
  },
};
