# This is a basic workflow to help you get started with Actions

name: Deploy to Hostinger (clockdown.xyz)

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: ["master"]
  # pull_request:
  # branches: ["hostinger"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Remove countdown* folders inside "/client/frontend/countdown-widget"
        working-directory: ./client/frontend/countdown-widget/src
        run: |
          rm -rf countdown*
          ls -la

      - name: Install build dependencies form 'templates editor' project
        working-directory: ./client/frontend/templates-editor
        run: npm install -g --legacy-peer-deps copyfiles cross-env webpack webpack-cli css-minimizer-webpack-plugin mini-css-extract-plugin

      - name: Build 'templates editor' frontend project
        working-directory: ./client/frontend/templates-editor
        run: npm run build

      - name: Build 'countdown-widget' frontend project
        working-directory: ./client/frontend/countdown-widget
        run: npm run build

      - name: Sync with Hostinger (clockdown.xyz)
        run: |
          echo "${{secrets.DEPLOY_KEY}}" > deploy_key
          chmod 600 ./deploy_key
          rsync -chav --delete \
            -e 'ssh -p 65002 -i ./deploy_key -o StrictHostKeyChecking=no' \
            --exclude=".git" \
            --exclude=".github" \
            --exclude="deploy_key" \
            --exclude="/client/frontend/countdown-widget" \
            --exclude="/client/frontend/templates-editor" \
            ./ u378434937@217.21.77.162:~/domains/clockdown.xyz/public_html/wp-content/plugins/clockdown
